"""add burnout_level to resource_profiles

Revision ID: 08c0979e940a
Revises: cb72e3098e82
Create Date: 2026-04-01 18:41:26.610596

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '08c0979e940a'
down_revision = 'cb72e3098e82'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resource_profiles', sa.Column('burnout_level', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('resource_profiles', 'burnout_level')
    # ### end Alembic commands ###
