"""remove unwanted columns from resource profile table

Revision ID: 2cc6996d93d3
Revises: 08c0979e940a
Create Date: 2026-04-01 22:31:19.401464

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2cc6996d93d3'
down_revision = '08c0979e940a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('resource_profiles', 'total_workload')
    op.drop_column('resource_profiles', 'workload_updated_at')
    op.drop_column('resource_profiles', 'domains')
    op.drop_column('resource_profiles', 'skills')
    op.drop_column('resource_profiles', 'jira_workload')
    op.drop_column('resource_profiles', 'github_workload')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resource_profiles', sa.Column('github_workload', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False))
    op.add_column('resource_profiles', sa.Column('jira_workload', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False))
    op.add_column('resource_profiles', sa.Column('skills', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('resource_profiles', sa.Column('domains', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('resource_profiles', sa.Column('workload_updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('resource_profiles', sa.Column('total_workload', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
