"""Add JobPosition model

Revision ID: 33567aa9bd58
Revises: h1a2b3c4d5e6
Create Date: 2026-03-18 23:02:08.198252

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '33567aa9bd58'
down_revision = 'h1a2b3c4d5e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_positions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_positions_name'), 'job_positions', ['name'], unique=True)
    op.drop_table('positions')
    op.drop_index(op.f('github_pr_vectors_embedding_hnsw_idx'), table_name='github_pr_vectors', postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_with={'m': '16', 'ef_construction': '64'}, postgresql_using='hnsw')
    op.add_column('resource_profiles', sa.Column('position_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'resource_profiles', 'job_positions', ['position_id'], ['id'])
    op.drop_column('resource_profiles', 'position')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resource_profiles', sa.Column('position', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'resource_profiles', type_='foreignkey')
    op.drop_column('resource_profiles', 'position_id')
    op.create_index(op.f('github_pr_vectors_embedding_hnsw_idx'), 'github_pr_vectors', ['embedding'], unique=False, postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_with={'m': '16', 'ef_construction': '64'}, postgresql_using='hnsw')
    op.create_table('positions',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=True, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('create_time', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('positions_pkey'))
    )
    op.drop_index(op.f('ix_job_positions_name'), table_name='job_positions')
    op.drop_table('job_positions')
    # ### end Alembic commands ###
