"""Update embedding models

Revision ID: 74767e85c847
Revises: g6h7i8j9k0l1
Create Date: 2026-01-25 20:13:40.214015

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '74767e85c847'
down_revision = 'g6h7i8j9k0l1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('github_pr_vectors', sa.Column('pr_description', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('github_pr_vectors', 'pr_description')
    # ### end Alembic commands ###
