"""remove unwanted columes

Revision ID: 7872ae357fb2
Revises: f4ad3d6891b5
Create Date: 2025-12-28 01:59:14.021890

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '7872ae357fb2'
down_revision = 'f4ad3d6891b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('org_integrations_github', 'github_webhook_secret')
    op.drop_column('org_integrations_github', 'github_private_key')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('org_integrations_github', sa.Column('github_private_key', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('org_integrations_github', sa.Column('github_webhook_secret', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
