from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
import pgvector.sqlalchemy


# revision identifiers, used by Alembic.
revision = 'a6e9a365daca'
down_revision = 'c2b07a956a7c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Enable pgvector extension
    op.execute('CREATE EXTENSION IF NOT EXISTS vector')
    
    op.create_table('github_pr_vectors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pr_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('pr_number', sa.Integer(), nullable=False),
    sa.Column('author_login', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('pr_title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('pr_url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=True),
    sa.Column('context', sa.Text(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_github_pr_vectors_author_id'), 'github_pr_vectors', ['author_id'], unique=False)
    op.create_index(op.f('ix_github_pr_vectors_author_login'), 'github_pr_vectors', ['author_login'], unique=False)
    op.create_index(op.f('ix_github_pr_vectors_embedding'), 'github_pr_vectors', ['embedding'], unique=False)
    op.create_index(op.f('ix_github_pr_vectors_pr_id'), 'github_pr_vectors', ['pr_id'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_github_pr_vectors_pr_id'), table_name='github_pr_vectors')
    op.drop_index(op.f('ix_github_pr_vectors_embedding'), table_name='github_pr_vectors')
    op.drop_index(op.f('ix_github_pr_vectors_author_login'), table_name='github_pr_vectors')
    op.drop_index(op.f('ix_github_pr_vectors_author_id'), table_name='github_pr_vectors')
    op.drop_table('github_pr_vectors')
    # ### end Alembic commands ###
