"""added job position to the ResourseProfile

Revision ID: ac132f3139d2
Revises: 74767e85c847
Create Date: 2026-01-25 20:45:42.266432

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'ac132f3139d2'
down_revision = '74767e85c847'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Backfill empty descriptions before enforcing NOT NULL
    op.execute("UPDATE github_pr_vectors SET pr_description = '' WHERE pr_description IS NULL")
    op.alter_column('github_pr_vectors', 'pr_description',
               existing_type=sa.VARCHAR(),
               server_default='',
               nullable=False)
    op.add_column('resource_profiles', sa.Column('position', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('resource_profiles', 'position')
    op.alter_column('github_pr_vectors', 'pr_description',
               existing_type=sa.VARCHAR(),
               existing_server_default='',
               server_default=None,
               nullable=True)
    # ### end Alembic commands ###
