"""add jira integration tables

Revision ID: b1c2d3e4f5a6
Revises: a6e9a365daca
Create Date: 2026-01-03 00:00:00.000000

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
import pgvector.sqlalchemy


# revision identifiers, used by Alembic.
revision = 'b1c2d3e4f5a6'
down_revision = 'a6e9a365daca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Create Jira Organization Integration table
    op.create_table('org_integrations_jira',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('jira_url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('jira_email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('project_keys', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    
    # Create Jira Issues table
    op.create_table('jira_issues',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('issue_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('issue_key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('project_key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('summary', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('issue_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('priority', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column('labels', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column('assignee_account_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column('assignee_display_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column('assignee_email', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column('reporter_account_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column('reporter_display_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column('issue_url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('jira_created_at', sa.DateTime(), nullable=True),
        sa.Column('jira_updated_at', sa.DateTime(), nullable=True),
        sa.Column('jira_resolved_at', sa.DateTime(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.Column('comments_json', sa.JSON(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_jira_issues_issue_id'), 'jira_issues', ['issue_id'], unique=True)
    op.create_index(op.f('ix_jira_issues_issue_key'), 'jira_issues', ['issue_key'], unique=False)
    op.create_index(op.f('ix_jira_issues_project_key'), 'jira_issues', ['project_key'], unique=False)
    op.create_index(op.f('ix_jira_issues_status'), 'jira_issues', ['status'], unique=False)
    op.create_index(op.f('ix_jira_issues_assignee_account_id'), 'jira_issues', ['assignee_account_id'], unique=False)
    
    # Create Jira Issue Vectors table for embeddings
    op.create_table('jira_issue_vectors',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('issue_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('issue_key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('project_key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('assignee_account_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=True),
        sa.Column('context', sa.Text(), nullable=True),
        sa.Column('metadata_json', sa.JSON(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_jira_issue_vectors_issue_id'), 'jira_issue_vectors', ['issue_id'], unique=True)
    op.create_index(op.f('ix_jira_issue_vectors_issue_key'), 'jira_issue_vectors', ['issue_key'], unique=False)
    op.create_index(op.f('ix_jira_issue_vectors_project_key'), 'jira_issue_vectors', ['project_key'], unique=False)
    op.create_index(op.f('ix_jira_issue_vectors_assignee_account_id'), 'jira_issue_vectors', ['assignee_account_id'], unique=False)
    
    # Create Developer Profiles table for user mapping (UC-002)
    op.create_table('developer_profiles',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('jira_account_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column('jira_display_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column('jira_email', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column('github_login', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column('github_id', sa.Integer(), nullable=True),
        sa.Column('internal_user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column('skills', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column('domains', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column('current_workload', sa.Integer(), nullable=False, server_default='0'),
        sa.Column('workload_updated_at', sa.DateTime(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_developer_profiles_jira_account_id'), 'developer_profiles', ['jira_account_id'], unique=True)
    op.create_index(op.f('ix_developer_profiles_github_login'), 'developer_profiles', ['github_login'], unique=True)
    op.create_index(op.f('ix_developer_profiles_internal_user_id'), 'developer_profiles', ['internal_user_id'], unique=False)
    
    # Create HNSW index for efficient vector similarity search on Jira issues
    op.execute('''
        CREATE INDEX IF NOT EXISTS jira_issue_vectors_embedding_idx 
        ON jira_issue_vectors 
        USING hnsw (embedding vector_l2_ops)
        WITH (m = 16, ef_construction = 64)
    ''')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Drop HNSW index
    op.execute('DROP INDEX IF EXISTS jira_issue_vectors_embedding_idx')
    
    # Drop Developer Profiles table
    op.drop_index(op.f('ix_developer_profiles_internal_user_id'), table_name='developer_profiles')
    op.drop_index(op.f('ix_developer_profiles_github_login'), table_name='developer_profiles')
    op.drop_index(op.f('ix_developer_profiles_jira_account_id'), table_name='developer_profiles')
    op.drop_table('developer_profiles')
    
    # Drop Jira Issue Vectors table
    op.drop_index(op.f('ix_jira_issue_vectors_assignee_account_id'), table_name='jira_issue_vectors')
    op.drop_index(op.f('ix_jira_issue_vectors_project_key'), table_name='jira_issue_vectors')
    op.drop_index(op.f('ix_jira_issue_vectors_issue_key'), table_name='jira_issue_vectors')
    op.drop_index(op.f('ix_jira_issue_vectors_issue_id'), table_name='jira_issue_vectors')
    op.drop_table('jira_issue_vectors')
    
    # Drop Jira Issues table
    op.drop_index(op.f('ix_jira_issues_assignee_account_id'), table_name='jira_issues')
    op.drop_index(op.f('ix_jira_issues_status'), table_name='jira_issues')
    op.drop_index(op.f('ix_jira_issues_project_key'), table_name='jira_issues')
    op.drop_index(op.f('ix_jira_issues_issue_key'), table_name='jira_issues')
    op.drop_index(op.f('ix_jira_issues_issue_id'), table_name='jira_issues')
    op.drop_table('jira_issues')
    
    # Drop Jira Organization Integration table
    op.drop_table('org_integrations_jira')
    # ### end Alembic commands ###

