"""add repo fields to github_pr_vectors

Revision ID: bcbee6ff3c73
Revises: ac132f3139d2
Create Date: 2026-02-26 23:29:00.769567

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'bcbee6ff3c73'
down_revision = 'ac132f3139d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('github_pr_vectors', sa.Column('repo_id', sa.Integer(), nullable=True))
    op.add_column('github_pr_vectors', sa.Column('repo_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.execute("UPDATE github_pr_vectors SET repo_id = 0 WHERE repo_id IS NULL")
    op.execute("UPDATE github_pr_vectors SET repo_name = '' WHERE repo_name IS NULL")
    op.alter_column('github_pr_vectors', 'repo_id', nullable=False)
    op.alter_column('github_pr_vectors', 'repo_name', nullable=False)
    op.alter_column('github_pr_vectors', 'pr_description',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_server_default=sa.text("''::character varying"))
    op.create_index(op.f('ix_github_pr_vectors_repo_id'), 'github_pr_vectors', ['repo_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_github_pr_vectors_repo_id'), table_name='github_pr_vectors')
    op.alter_column('github_pr_vectors', 'pr_description',
               existing_type=sa.VARCHAR(),
               nullable=False,
               existing_server_default=sa.text("''::character varying"))
    op.drop_column('github_pr_vectors', 'repo_name')
    op.drop_column('github_pr_vectors', 'repo_id')
    # ### end Alembic commands ###
