"""add organization_name to github org integration

Revision ID: c2b07a956a7c
Revises: 7872ae357fb2
Create Date: 2025-12-28 02:06:02.366797

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'c2b07a956a7c'
down_revision = '7872ae357fb2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('org_integrations_github', sa.Column('org_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('org_integrations_github', 'org_name')
    # ### end Alembic commands ###
