"""add teams table and team_id to resource_profiles

Revision ID: cb72e3098e82
Revises: 9f8e7d6c5b4a
Create Date: 2026-03-29 08:58:58.164459

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'cb72e3098e82'
down_revision = '9f8e7d6c5b4a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Create teams table
    op.create_table(
        "teams",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_teams_name"), "teams", ["name"], unique=True)

    # Add team_id to resource_profiles
    op.add_column("resource_profiles", sa.Column("team_id", sa.Integer(), nullable=True))
    op.create_foreign_key(
        "fk_resource_profiles_team_id_teams",
        "resource_profiles",
        "teams",
        ["team_id"],
        ["id"],
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Remove team_id from resource_profiles
    op.drop_constraint("fk_resource_profiles_team_id_teams", "resource_profiles", type_="foreignkey")
    op.drop_column("resource_profiles", "team_id")

    # Drop teams table
    op.drop_index(op.f("ix_teams_name"), table_name="teams")
    op.drop_table("teams")
    # ### end Alembic commands ###
