"""add jira oauth token table

Revision ID: d8e9f0a1b2c3
Revises: b1c2d3e4f5a6
Create Date: 2026-01-03 12:00:00.000000

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'd8e9f0a1b2c3'
down_revision = 'b1c2d3e4f5a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jira_oauth_tokens',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('cloud_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column('jira_site_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column('access_token', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('refresh_token', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column('expires_at', sa.DateTime(), nullable=False),
        sa.Column('scope', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column('token_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_jira_oauth_tokens_cloud_id'), 'jira_oauth_tokens', ['cloud_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_jira_oauth_tokens_cloud_id'), table_name='jira_oauth_tokens')
    op.drop_table('jira_oauth_tokens')
    # ### end Alembic commands ###
