"""add github org integration table

Revision ID: f4ad3d6891b5
Revises: 773aea848bdc
Create Date: 2025-12-28 00:13:22.519673

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'f4ad3d6891b5'
down_revision = '773aea848bdc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('org_integrations_github',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('github_install_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('github_private_key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('github_webhook_secret', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('org_integrations_github')
    # ### end Alembic commands ###
