"""add hnsw index github pr vectors

Revision ID: g6h7i8j9k0l1
Revises: f5g6h7i8j9k0
Create Date: 2026-01-17 00:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'g6h7i8j9k0l1'
down_revision = 'f5g6h7i8j9k0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Create HNSW index for efficient vector similarity search on GitHub PR embeddings
    op.execute('''
        CREATE INDEX IF NOT EXISTS github_pr_vectors_embedding_hnsw_idx 
        ON github_pr_vectors 
        USING hnsw (embedding vector_cosine_ops)
        WITH (m = 16, ef_construction = 64)
    ''')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Drop HNSW index
    op.execute('DROP INDEX IF EXISTS github_pr_vectors_embedding_hnsw_idx')
    # ### end Alembic commands ###
